apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
 name: web # Название Pod
 labels: # Метки в формате key: value
    app: web
spec: # Описание Pod
 initContainers:
  - name: initcontainer # Название контейнера
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app # Название контейнера
      mountPath: /app

 containers: # Описание контейнеров внутри Pod
 - name: web # Название контейнера
   image: nellykey/hw1:latest-dev
   readinessProbe:
     httpGet: 
      path: /index.html
      port: 80
     tcpSocket: 
      port: 8000
   livenessProbe:
     tcpSocket: 
      port: 8000
 volumes:
  - name: app
    emptyDir: {}
